disabled_rules: # rule identifiers to exclude from running
  - notification_center_detachment
  - identifier_name

opt_in_rules: # some rules are only opt-in
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - joined_default_parameter
  - literal_expression_end_indentation
  - unneeded_parentheses_in_closure_argument
  - operator_usage_whitespace
  - trailing_closure
  - private_action

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods/Alamofire
  - Pods/Mockingjay
  - Pods/URITemplate
  - vendor/bundle
  - APIClient-ExampleTests

comma: error
force_cast: warning 
force_try: warning
return_arrow_whitespace: error

trailing_whitespace:
  ignores_empty_lines: true
line_length:
  warning: 250
  error: 350
type_body_length:
  warning: 300
  error: 400
cyclomatic_complexity:
  ignores_case_statements: true
file_length:
  warning: 500
  error: 1000
function_body_length:
  warning: 80
  error: 100
warning_threshold: 30
reporter: "xcode"
